# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Site
email:            info@site.com
description:      Site Template
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'http://site.com' # The base hostname & protocol for your site
github_username:  
twitter_username: 

# Build settings
markdown:  kramdown
permalink: pretty
paginate:  36
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - setup.sh
  - deploy.sh
  - build.sh
  - serve.sh
  - check_site.sh
  - watch_site.sh
  - .gitignore
  - README.md

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  me:
    name: site user
    bio: the site user
    email: user@site.com
  
